name: build and publish to aliyun server
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
#    - run: npm test
    - name: Deploy to Aliyun server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEA4u97HE8PRMD7G19WNsHfhsS1HSsuVrxNr0dx2G8uexpPndrZ
1gcafuAilsDldhUA3/r6voo573+eQJKNtkTzOWAD/EJMtSjdzjTW/oZg16pLwaqn
UyggHDaCl5IO8NkF460hdvVm6/aDqacIbGAqKS2s87HTlGaaldnvTBSatGfl/UFB
oXVCcti8qL+k6VUXL/DPElN8G+ZHUirFPRTPIevFYXZWAqs8cG11SCSFtsowBnBh
9yM7L5MVgr6uoYiAM+IqNdBR0jH1P5ftCqtD9eUiUMVcfFb/w3tYNPEqU8qd7aBZ
DPOvj1wUllXHdZZ014q9TjxLkWznNca30nGQnb5oKHlbpLBuqWRaeF5aIjIKCduq
BNZYUjk5zx7dRLM0bstkql7EwKOsBAQjtWE2jetj/uNB6xgJEElBzLu3eoLimPPp
I9yoQaadzytm1BLhExhyfHQigYxyXE+wj8jMvsmGvJ9XxRDM+FljglCvii5+rQ5B
3vYcJWFTW73Xqtfhw9qLaW7Cn3+NyuHU9jwz/GlZk1GRiR16yshlntOeNnPANGwZ
WJjPj0ypULEU9HTP14z7ybLOJscrzg/rZeANtqriBiz24OkHtomr3rDYuSYyQoi3
twm3UzVVaPTXBX/Im9UAQ+Dk5YgHADVT1TWRQg7zKXlJ5oAT+GDGVFNuy50CAwEA
AQKCAgBAz75sRlQJAch1d9PqjZImLjW/n957HQpevdvQwWgX9lq4rZE7JAo4JBEc
1vhxsevvDAHiux1yvhLXREO+w5BnWXmp6NF5h7NZOhQQ2xX7YgKCzBc/k50gEZ1Y
Znln5cNd08tT6yA60cumfzLTqN9BpW7YpnfT0T3jADvskZHhZi70FlgFIbUZkbbH
xvv1O70EjxTEmh0+5pSF7fsox7GkcW6MuDw2ROtc/JXbRbr+il4O6LfB2kkD/FDP
Z1/+eDqNFtGRTu6fRm9RezVSr7kYGBml0cfpJvuiu65kaF/7UEmsXPgxz8LbAaRL
jzII7jBugowwNN4sKVsbK6bCLnbrXJBLsIpqj6iTST1VsyPN2V1/Oz2wiiKBtgpT
HSY87ea90vGzgTiZbFYzqANRi8U6eGavQr3m+yXzdRkrttV24tG5wQLiR6Vb2JyM
QBvG3xu0MTFBHhP3JqdtxAzKnCyK9UCHrEJ7t0a3w0zBahjanNbwQ99nHOew0if2
JZsSZEoJT59TGoES2wx73aoBFDQzPzdw4C/LWg9KYsMjzPXeDrVTcGHHeupMsalT
jFSxcl5jL/Hyytt3Tsef1Qc5RoZJKE+dBvyBr3EAuaFWtqM5WaIilNtlro0vywvW
dYXXWCFOSBnJQLmV1giRFb4vwy/DfMUJmBxDcf+bgLfA8F0sjQKCAQEA81n+mh2h
iY24aBPOMS5S7HC5oN2HhUaNy/m/Cs8RZIrWG5MxnfFH0B6p2Hv15Q2QGc3NOTvl
G8lJ7qAyuhy6ZnX4QUO01N7uboRwnORjC6L4YPEMGzFn9G7ISWGfgXROHo54YePD
UBLhHuW4/H6bumFhZF1Yq+gNBwE2CPS7Niwk9at6ejM3kz3a7LfFWpbDe5cKVzaX
whUXuTd6jAnBo0b0kqjfwEIucEVbptFooie7b2AIRwOip5Klq/GIi2CxjJj4fH04
V+epeerkR6FS5wOGwuh92FIWfG1XK46JOtjMkywhzcI3ZeSmxljricJ/V29KLZ+u
XzZt0YJtC1FQUwKCAQEA7rsOYfgskOdwWhu0cRKTMsmnpUPJbxA1zhJ10W2SZ4TS
V2L6vo3fXeP8Kawhe342TDrY5Fd9Y26xl08vIYZt/O46G3KMvoIBHTQ00WRE+ZWt
Owj9y2uo+rBDbkpAe8TU7RDmjX2+2KSMXI3/gdC3AnKZoJ+6OABl9eQDPtVzPpHc
F2dwcRAsfjtaoCNZaxT5v0LQbw4thqLtVocwBvHtbXGoDD93wYJDk/7kWDxF2TJd
+0M5rOtacexq3hLO2Y7Pmqg6240/vnTVwVAihvOySA10E2pU3PB0bVuKeIOS2d/z
rKz0yCh8RU6UmQVQeqTUhH3A43/vTmkSP6xESVS2TwKCAQB8LxzCQQTCUVQdqJ28
c0tV5WCVOveBh7Ost9JKDcluaXtBryfO1eYzyrIaC4g8T2OOB3wHDQ2p1FqqL44z
c52b0+/QPmD1kJ5UP7nIFrSEp7HgpqHq7peCIVaMPAlN4rBK36GHMtfk8P146vov
v9xwjGlK8mfhshWT0YZlo5410uk5hTyHR8PAm/wweMd5px4y360jPHTNUj49ApbD
B+eNDxSYEx272wofuQVAZ/Thay03dOZEdxJ2OVvaFvP7TGjOuvFzdeNe2JWf5cKA
206XHTGUHVi7H4jiDlpBnAdjxGcBY7AMdGQY10pUReRM9LhPQje0eJxfckMwe0Jy
WBiJAoIBACbzhEw91t+ps24wWQed9UBzIJRZdBNX/L9ryadrDlkvlbZGYw0WTtyd
5zXRbQEePbPAYkUXdVD07ar3c4Qvz+BV6ksyLH6k7ZObQgbsKkjiwAoC1I4NOdv1
SHtFSDIpkmg/uq5ZVvs4FeLAFHFU4ZdXpXNMvHCIuBofotvsrcoGuHdlHDaGYgwS
mR3JxrwvBvTK7QFBufHewYS9t/taG9gglD+zV1HOdEJAc3dmFitzCVyGwnFRUUeH
QISNYwyiPYNJcZkC+eSUYZASCCAmwO76qvbEAaau4QA60GQLa7l6zeJdse66lFQm
lx5EfLYWEMqxTfiQljYf9KdI7zdbyAcCggEAJX7Mk7ygFn/lin8wGaqA0/nTK43E
QZ/VNbF+Mq43v0waWiMSDvxd4DroXhy/oSBKGV1e1YkmztGegjL8X70Y5NUABaJh
EBfW+ubzJKU66zDH95NtmNH5U58DWTB20egutPBXlqoY8fc86e4cn1nuE84P1WlO
MwN8LkrdBqTDKwPYjpolVH8OnIXFcdruuOIunenWebymm8ehXE3aqdyJvov8ptVo
cD4TZ+GRlZ+VQMy5y0HZtf9RzHb66/pirvmRJniQRT+vkh4gDYASa7SWZJXVILHw
OlMyRwMO3R2tnuF8RQU7Of2fl6N/s4rofk76A5Ok0vwA1bZDxx19ZB8Lfg==
-----END RSA PRIVATE KEY-----'
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "build/"
        REMOTE_HOST: 47.97.61.227
        REMOTE_USER: "root"
        TARGET: "/data/test/"
